name: Check

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Run astro check
        run: pnpm astro check

